
--Tables Creation
CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    Family_Members VARCHAR2(200)
);

CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Book_Title VARCHAR2(100) NOT NULL UNIQUE,
    Book_Price NUMBER(10, 2) CHECK (Book_Price > 0),
    Book_Quantity NUMBER CHECK (Book_Quantity >= 0)
);

CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER REFERENCES Customers(CustomerID),
    ProductID NUMBER REFERENCES Products(ProductID),
    OrderDate TIMESTAMP DEFAULT SYSTIMESTAMP
);

--Index 
CREATE INDEX idx_cust_prod ON Orders(CustomerID, ProductID);
